[project]
name = "dfdrift"
version = "0.1.0"
description = "DataFrame schema drift detection and alerting"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.2",
]

[tool.setuptools.packages.find]
include = ["dfdrift*"]
